name: Android CI

on:
  push:
    branches:
      - 'develop/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.FIREBASE_CREDENTIALS_JSON }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build and run tests
      run: |
        echo ${{ secrets.API_KEY }} | base64 --decode > ./local.properties
        ./gradlew build
        ./gradlew assembleDebugAndroidTest

    - name: Run tests in Firebase Test Lab
      env:
        GCLOUD_SERVICE_KEY: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
        echo ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 --decode > ./app/google-services.json
        gcloud auth activate-service-account --key-file=./app/google-services.json
        gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}
        gcloud firebase test android run \
          --type instrumentation \
          --app app/build/outputs/apk/debug/app-debug.apk \
          --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
          --device model=Pixel8,version=34,locale=ja_JP,orientation=portrait
