name: ktlint

on: [push]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Change Permission
        run: chmod +x ./gradlew

      - name: Execute Gradle check
        run: ./gradlew check
